### ISSUE TITLE
jekyll_1  | /usr/jekyll/bin/entrypoint: line 34: /usr/local/bin/jekyll: No such file or directory

### ISSUE THREAD

**Issue by skymfc** [play-with-docker/training#4]
The below error popout after excuted "docker-compose up".
jekyll_1  | /usr/jekyll/bin/entrypoint: line 34: /usr/local/bin/jekyll: No such file or directory

**Comment by ManoMarks** [comment]
This is a stale repo that was used for testing awhile. If you're having issues with training.play-with-docker.com, please file an issue here: https://github.com/play-with-docker/play-with-docker.github.io
